linux launcher validations

diff --git a/linux_afni_docker b/linux_afni_docker
--- a/linux_afni_docker
+++ b/linux_afni_docker
@@ -14,7 +14,7 @@ set prog = "linux_afni_docker"
 ## default docker image
 set dock_img = "discoraj/afni_docker_universal:latest"
 set pull = "missing"
-set disp = "DISPLAY=${DISPLAY}"
+set disp = ${DISPLAY}
 
 set narg = 1
 @  amax = $#argv - 0
@@ -35,6 +35,8 @@ while ( $narg <= $amax )
     endif
     @ narg ++
 end
+
+
 
 ################################################
 ## check to see if things exist / are installed
@@ -58,6 +60,36 @@ if ( "$docker_bin" == "" ) then
     echo "Is Docker installed?"
     echo "If Docker is installed, can you open it?"
     echo "If not, check your paths or manually launch it." ; echo
+    exit 1
+
+endif
+
+######################################################
+## Check for docker group and if the users is a member.
+
+set docker_grp_exists = `compgen -g | grep docker`
+if ( "$docker_grp_exists" == "" ) then
+
+    echo ; echo "** ERROR: The docker group does not exist." ; echo
+    echo "Please create the docker group and add yourself to it."
+    echo "Then restart your computer."
+    echo "If you are in the docker group, there may be a problem with this program..."
+    echo "Please post the error to: https://discuss.afni.nimh.nih.gov" ; echo
+    
+    exit 1
+
+endif
+
+set docker_member = `groups $USER | grep docker`
+if ( "$docker_member" == "" ) then
+
+    echo ; echo "** ERROR: You don't seem to be in the docker group." ; echo
+    echo "This may cause issues with permissions when running the docker container."
+    echo "If you haven't already, you may want to add yourself to the docker "
+    echo "group and restart your computer."
+    echo "If you are in the docker group, there may be a problem with this program..."
+    echo "Please post the error to: https://discuss.afni.nimh.nih.gov" ; echo
+    
     exit 1
 
 endif
